#!/bin/bash
# Cross-compiles real upstream fontconfig 2.13.1
# (gitlab.freedesktop.org/fontconfig/fontconfig, tag 2.13.1 --
# deliberately not the current ~2.17+ series, which moved to a
# meson-only build; 2.13.1 is the last release with a clean
# autotools-only build, avoiding pulling meson into this phase of the
# GTK port) against the freshly-built expat + freetype2.
#
# `configure` was pre-generated by running `NOCONFIGURE=1 ./autogen.sh`
# once (this succeeded cleanly on the first try, no xorg-macros needed).
#
# --with-cache-dir points at a runtime-writable path this project's
# rootfs actually supports (/usr/var/cache/fontconfig); fontconfig can
# build its font list by scanning --with-default-fonts directly on
# first FcInit() if no cache exists yet, so a missing/empty cache dir
# at runtime is expected to degrade gracefully, not fail -- verify
# this live in QEMU (see TODO.md Phase 39) rather than assuming it.
#
# --sysconfdir=/usr/etc (a TARGET-absolute path, not a build-host
# path): fontconfig bakes sysconfdir's fonts/fonts.conf location into
# the library at compile time as its default config-file search path
# (FcConfigFilename() in fccfg.c). This must match wherever the
# runtime rootfs actually ships fonts.conf (userland/mkrootfs.sh /
# src/xfttest/build.sh install it to /usr/etc/fonts/fonts.conf), not
# this build host's own directory layout -- an earlier version of this
# script wrongly passed $PREFIX/etc here (a path that only exists on
# the build machine), which built fine but failed at runtime with
# "Fontconfig error: Cannot load default config file", caught live in
# QEMU. `make install`'s own attempt to write to that path is still
# safely redirected by DESTDIR below, same as the cache-dir mkdir.
#
# -DFC_NO_MT: fcatomic.h's __APPLE__ branch calls real Darwin
# libkern/OSAtomic.h primitives (OSMemoryBarrier/
# OSAtomicCompareAndSwap64Barrier) this project's minimal libc doesn't
# implement. FC_NO_MT forces fontconfig's plain non-atomic fallback
# path instead of chasing a libkern shim -- safe here since nothing in
# this project's X11 client processes uses fontconfig from more than
# one thread.
#
# Installed into build/gtk-deps-install (see src/expat/build.sh's
# comment for why this is a separate prefix from xorg-deps-install).
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"
ROOT="$(cd ../.. && pwd)"

CLANG="$ROOT/build/tools/asteros-sdk/bin/clang -std=gnu23"
PREFIX="$ROOT/build/gtk-deps-install"
ZLIB_PREFIX="$ROOT/build/xorg-deps-install"

export PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig:$ZLIB_PREFIX/lib/pkgconfig"
export PKG_CONFIG_LIBDIR="$PKG_CONFIG_PATH"

./configure --host=x86_64-apple-darwin19 --prefix="$PREFIX" \
	CC="$CLANG" \
	CPPFLAGS="-I$ZLIB_PREFIX/include -DFC_NO_MT" LDFLAGS="-L$ZLIB_PREFIX/lib" \
	FREETYPE_CFLAGS="-I$PREFIX/include/freetype2" \
	FREETYPE_LIBS="-L$PREFIX/lib -lfreetype" \
	--disable-shared --enable-static \
	--disable-docs --with-expat="$PREFIX" \
	--sysconfdir=/usr/etc \
	--with-cache-dir=/usr/var/cache/fontconfig \
	--with-default-fonts=/usr/share/fonts \
	--with-add-fonts= \
	--disable-libxml2

make -j"$(sysctl -n hw.ncpu)"

# fontconfig's own install-data-local rule mkdir's the *runtime*
# --with-cache-dir path (/usr/var/cache/fontconfig) directly on
# whatever machine runs `make install` -- fine on a real target
# root, but on this build host that's the real, read-only /usr/var.
# DESTDIR staging (which the rule already respects via
# $(DESTDIR)$(fc_cachedir)) redirects that mkdir under a throwaway
# staging dir instead; only the real $PREFIX subtree is then merged
# into the shared gtk-deps-install prefix.
DESTDIR_STAGE="$ROOT/build/fontconfig-destdir"
rm -rf "$DESTDIR_STAGE"
make install DESTDIR="$DESTDIR_STAGE"
mkdir -p "$PREFIX"
cp -R "$DESTDIR_STAGE$PREFIX/." "$PREFIX/"
rm -rf "$DESTDIR_STAGE"

echo "installed: $PREFIX/lib/libfontconfig.a, $PREFIX/include/fontconfig/fontconfig.h"
