#!/bin/bash
# Cross-compiles real upstream expat 2.8.3 (github.com/libexpat/libexpat,
# tag R_2_8_3) -- fontconfig's XML config-file parser dependency.
#
# Installed into a SEPARATE shared prefix, build/gtk-deps-install, not
# the existing build/xorg-deps-install -- see src/freetype2/build.sh's
# comment (or TODO.md's Phase 39 writeup) for why: fontconfig/libXft/
# freetype2 fully collide with files src/xft-stub/build.sh installs
# into xorg-deps-install on every rebuild, so the real font stack gets
# its own prefix to avoid a clobber race with xpaint's existing,
# untouched xft-stub usage.
#
# `configure` was pre-generated by running `LIBTOOLIZE=glibtoolize
# autoreconf -fi` once (upstream ships no committed configure script;
# macOS's libtoolize is named glibtoolize).
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"
ROOT="$(cd ../.. && pwd)"

CLANG="$ROOT/build/tools/asteros-sdk/bin/clang -std=gnu23"
PREFIX="$ROOT/build/gtk-deps-install"

export PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig"
export PKG_CONFIG_LIBDIR="$PREFIX/lib/pkgconfig"

./configure --host=x86_64-apple-darwin19 --prefix="$PREFIX" \
	CC="$CLANG" \
	--disable-shared --enable-static \
	--without-docbook --without-tests --without-examples

make -j"$(sysctl -n hw.ncpu)"
make install

echo "installed: $PREFIX/lib/libexpat.a, $PREFIX/include/expat.h"
