#!/bin/bash
# Cross-compiles real upstream libXrender 0.9.12
# (gitlab.freedesktop.org/xorg/lib/libxrender, tag libXrender-0.9.12)
# against this project's vendored X11 stack, using the same
# autotools-via-cross-clang recipe already proven manually for libXi
# (see src/libXi/config.log) but committed here as a reusable script --
# the first of the four new X11 extension libraries GTK3's X11 backend
# requires (libXrender, libXfixes, libXrandr, libXcursor). No
# dependency on the other three; must build first since libXrandr and
# libXcursor both link against it.
#
# `configure` was pre-generated by running `NOCONFIGURE=1
# ACLOCAL_PATH=$ROOT/src/xorg-util-macros LIBTOOLIZE=glibtoolize
# ./autogen.sh` once (upstream ships no committed configure script;
# needs the vendored xorg-macros.m4 >= 1.8 already vendored at
# src/xorg-util-macros, and macOS's libtoolize is named glibtoolize).
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"
ROOT="$(cd ../.. && pwd)"

CLANG="$ROOT/build/tools/asteros-sdk/bin/clang -std=gnu23"
PREFIX="$ROOT/build/xorg-deps-install"

export PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig"
export PKG_CONFIG_LIBDIR="$PREFIX/lib/pkgconfig"

./configure --host=x86_64-apple-darwin19 --prefix="$PREFIX" \
	CC="$CLANG" \
	--disable-shared --enable-static

make -j"$(sysctl -n hw.ncpu)"
make install

echo "installed: $PREFIX/lib/libXrender.a, $PREFIX/include/X11/extensions/Xrender.h"
